name: build
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript imagemagick
          npm i slugify gray-matter marked
      - name: build portfolio
        run: |
          mkdir -p imgs
          for f in pdfs/*.pdf; do
            [ -f "$f" ] || continue
            slug=$(basename "$f" .pdf | tr '[:upper:]' '[:lower:]' | tr ' ' -)
            scripts/convert.sh "$f" "$slug"
          done
          node scripts/make_pages.js
      - name: build blog
        run: node scripts/build_blog.js
      - uses: actions/upload-pages-artifact@v2
        with:
          path: .
  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v2
