backend:
  name: git-gateway
  branch: main
media_folder: "imgs/uploads"
public_folder: "/imgs/uploads"
collections:
  - name: "posts"
    label: "Статьи"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: "title", label: "Заголовок"}
      - {name: "date", label: "Дата", widget: "datetime"}
      - {name: "description", label: "Описание", widget: "string"}
      - {name: "body", label: "Текст", widget: "markdown"}